# Default initial positions for mycobot_600's ros2_control fake system

initial_positions:
  joint2_to_joint1: -2.6
  joint3_to_joint2: -2.02
  joint4_to_joint3: -2.146
  joint5_to_joint4: -0.558
  joint6_to_joint5: 1.518
  joint6output_to_joint6: 0.68