# Default initial positions for mycobot_600's ros2_control fake system

initial_positions:
  joint2_to_joint1: 0.436332
  joint3_to_joint2: -1.90241
  joint4_to_joint3: -2.68781
  joint5_to_joint4: -0.122173
  joint6_to_joint5: 1.5708
  joint6output_to_joint6: 2.02458
  




