# Default initial positions for mycobot_600's ros2_control fake system

initial_positions:
  joint2_to_joint1: 2.6
  joint3_to_joint2: -0.75
  joint4_to_joint3: 1.69297
  joint5_to_joint4: -2.49582
  joint6_to_joint5: -1.57
  joint6output_to_joint6: 2.63545