mycobot_pro_600_arm:
  kinematics_solver: trac_ik_kinematics_plugin/TRAC_IKKinematicsPlugin
  kinematics_solver_timeout: 0.5
  kinematics_solver_attempts: 10
  solve_type: Manipulation1 # Options: Speed, Distance, Manipulation1, Manipulation2
  

