mycobot_pro_600_arm:
  kinematics_solver: trac_ik_kinematics_plugin/TRAC_IKKinematicsPlugin
  kinematics_solver_timeout: 0.01
  kinematics_solver_attempts: 5
  solve_type: Distance  # Options: Speed, Distance, Manipulation1, Manipulation2
  

